# audio and videos previews
zencoder_enabled: false
# zencoder_api_key: '{{zhdk_zencoder_api_key}}'
# zencoder_test_mode: True

# backups
# db_backups_enabled: False

# branding
madek_site_title: "Media Archive"
madek_welcome_title: "Welcome to Madek!"

# madek_webapp_html_extra_head_start: |
#   <!--
#        __       __                  __            __
#   /  \     /  |                /  |          /  |
#   $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
#   $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
#   $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
#   $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
#   $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
#   $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
#   $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/
#
#   -->

# madek_webapp_html_extra_head_end: |
#   <link rel="stylesheet" type="text/css" href="/local-theme.css">
